version: '3'

services:
  goravel:
    build:
      context: .
    ports:
      - "3000:3000"
    # restart: always

  db:
    image: postgres:16-alpine
    shm_size: 128mb
    environment:
      POSTGRES_DB: goravel
      POSTGRES_USER: goravel
      POSTGRES_PASSWORD: g0r4v3l
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"